[package]
name = "noct-screen"
version = "0.1.0"
edition = "2021"

build = "build.rs"


[dependencies]
noct-logger = { path = "../noct-logger" }


[build-dependencies]
bindgen = { version = "0.72.0" }
