[package]
name = "noct-audio"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
noct-logger = { path = "../noct-logger" }
noct-il = { path = "../noct-il" }

[build-dependencies]
cbindgen = { version = "0.29.0" }