[package]
name = "noct-ps2"
version = "0.1.0"
edition = "2024"

[dependencies]
x86 = "0.52.0"
noct-logger = { path = "../noct-logger" }
noct-input = { path = "../noct-input" }
noct-interrupts = { path = "../noct-interrupts" }