name: Pull request tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Just lists all version of clang
        run: sudo apt list "clang-*"

      - name: Step 1 - Software installation
        run: |
          sudo apt install nasm python3 build-essential xorriso grub-pc-bin mtools llvm lld ninja-build cmake

      - name: Step 1.1 - Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y

      - name: Step 1.2 - Install toolchain
        run: |
          rustup toolchain install nightly-2025-04-01
          rustup component add rust-src --toolchain nightly-2025-04-01-x86_64-unknown-linux-gnu

      - name: Step 2 - Configuring the kernel
        run: bash tools/build/make_builds.sh

      - name: Step 3 - Build all
        run: bash tools/build/ci.shs
