[package]
name = "noct-iso9660"
version = "0.1.0"
edition = "2021"

[dependencies]
iso9660_simple = { version = "0.1.8", default-features = false }
noct-dpm-sys = { path = "../noct-dpm-sys" }
noct-fs-sys = { path = "../noct-fs-sys" }
noct-logger = { path = "../noct-logger" }
